
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const ProductDetail = lazy(() => import("./pages/ProductDetail.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/product-detail", element: <ProductDetail />},
	{ path: "/productdetail", element: <ProductDetail />},

];
